from typing import Any


NODE_LIBRARY: list[dict[str, Any]] = [
    {
        "id": "basic.python",
        "name": "Python代码输入",
        "category": "01-基础工具",
        "description": "在节点内执行自定义 Python 代码并输出结构化结果。",
        "inputs": ["df_input", "context"],
        "outputs": ["df_factor"],
        "params": [
            {"key": "timeout", "type": "number", "defaultValue": 6},
            {"key": "strictSchema", "type": "boolean", "defaultValue": True},
            {
                "key": "script",
                "type": "string",
                "defaultValue": "import pandas as pd\ndf_factor = df_input[['date','symbol']].copy()\ndf_factor['factor1'] = 0.0",
            },
        ],
    },
    {
        "id": "data.market",
        "name": "行情数据读取",
        "category": "01-基础工具",
        "description": "读取本地行情样本并输出基础行情表。",
        "inputs": [],
        "outputs": ["market_df"],
        "params": [{"key": "lookback", "type": "number", "defaultValue": 180}],
    },
    {
        "id": "feature.build",
        "name": "特征工程构建",
        "category": "02-特征工程",
        "description": "执行去极值、标准化、中性化等预处理。",
        "inputs": ["market_df"],
        "outputs": ["feature_df"],
        "params": [{"key": "normalize", "type": "boolean", "defaultValue": True}],
    },
    {
        "id": "ml.xgboost",
        "name": "XGBoost模型",
        "category": "03-机器学习",
        "description": "训练模型并输出预测值与特征重要性。",
        "inputs": ["feature_df", "label_df"],
        "outputs": ["pred_df", "feature_importance"],
        "params": [{"key": "learningRate", "type": "number", "defaultValue": 0.05}],
    },
    {
        "id": "factor.custom",
        "name": "自定义因子构建",
        "category": "04-因子相关",
        "description": "将模型输出转换为标准因子格式(date/symbol/factor1)。",
        "inputs": ["pred_df"],
        "outputs": ["factor_df"],
        "params": [{"key": "factorName", "type": "string", "defaultValue": "factor1"}],
    },
    {
        "id": "backtest.future",
        "name": "期货回测",
        "category": "05-回测相关",
        "description": "基于调仓频率和交易成本运行期货策略回测。",
        "inputs": ["factor_df"],
        "outputs": ["report_json"],
        "params": [{"key": "feeBps", "type": "number", "defaultValue": 4}],
    },
    {
        "id": "factor.pca",
        "name": "PCA因子构建",
        "category": "06-线下专属",
        "description": "综合模型特征重要度进行 PCA 复合因子生成。",
        "inputs": ["feature_importance", "feature_df"],
        "outputs": ["pca_factor"],
        "params": [{"key": "components", "type": "number", "defaultValue": 5}],
    },
]
